
# Dados de acesso ao Supabase (Conexão PostgreSQL)
DB_HOST = "aws-1-sa-east-1.pooler.supabase.com"
DB_PORT = 5432
DB_NAME = "postgres"
DB_USER = "postgres.clqigwvbhdzxegfcvlqn"
DB_PASSWORD = "c1c2c3c4C5@"

# Supabase Auth
SUPABASE_URL = "https://clqigwvbhdzxegfcvlqn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNscWlnd3ZiaGR6eGVnZmN2bHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0NzA5NzcsImV4cCI6MjA3OTA0Njk3N30.fYB6y9xI1y4NqExZbhaBTuFtgb014Xrop-CXmNTAvH8"

# String de conexão completa
# DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# Configurações da aplicação
# TABELA_CONTABILIDADE = "contabilidade"
# PASTA_DADOS = "dados"
# SEPARADOR_CSV = ";"
# ENCODING = "utf-8"
